[package]
name = "simutrans-factory-graph"
version.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
pak-core = { path = "../crates/pak-core" }
serde.workspace = true
base64 = "0.22"

